learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: epoch

checkpointing:
  _target_: assembly.callbacks.EpochCheckpointingCallback
  dirpath: ./output/${experiment_name}
  monitor_candidates:
    - eval/part_acc
    - val/loss
  every_n_epochs: 50
  save_weights_only: False

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
